//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnlaceFiscal.EFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.enlacefiscal.namespace", ConfigurationName="EFService.wsAPIxmlSOAP")]
    public interface wsAPIxmlSOAP {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/generarCFD", ReplyAction="*")]
        System.IAsyncResult BegingenerarCFDi(EnlaceFiscal.EFService.generarCFDiRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.generarCFDiResponse EndgenerarCFDi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/informacionCFD", ReplyAction="*")]
        System.IAsyncResult BegininformacionCFDi(EnlaceFiscal.EFService.informacionCFDiRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.informacionCFDiResponse EndinformacionCFDi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/cancelarCFD", ReplyAction="*")]
        System.IAsyncResult BegincancelarCFDi(EnlaceFiscal.EFService.cancelarCFDiRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.cancelarCFDiResponse EndcancelarCFDi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/obtenerSaldo", ReplyAction="*")]
        System.IAsyncResult BeginobtenerSaldo(EnlaceFiscal.EFService.obtenerSaldoRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.obtenerSaldoResponse EndobtenerSaldo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/solicitarXML", ReplyAction="*")]
        System.IAsyncResult BeginsolicitarXML(EnlaceFiscal.EFService.solicitarXMLRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.solicitarXMLResponse EndsolicitarXML(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/probarConexion", ReplyAction="*")]
        System.IAsyncResult BeginprobarConexion(EnlaceFiscal.EFService.probarConexionRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.probarConexionResponse EndprobarConexion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/solicitarQR", ReplyAction="*")]
        System.IAsyncResult BeginsolicitarQR(EnlaceFiscal.EFService.solicitarQRRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.solicitarQRResponse EndsolicitarQR(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="/enviarCorreo", ReplyAction="*")]
        System.IAsyncResult BeginenviarCorreo(EnlaceFiscal.EFService.enviarCorreoRequest request, System.AsyncCallback callback, object asyncState);
        
        EnlaceFiscal.EFService.enviarCorreoResponse EndenviarCorreo(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class generarCFDiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarFolio;
        
        public generarCFDiRequest() {
        }
        
        public generarCFDiRequest(string generarFolio) {
            this.generarFolio = generarFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class generarCFDiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarResult;
        
        public generarCFDiResponse() {
        }
        
        public generarCFDiResponse(string generarResult) {
            this.generarResult = generarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class informacionCFDiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoFolio;
        
        public informacionCFDiRequest() {
        }
        
        public informacionCFDiRequest(string infoFolio) {
            this.infoFolio = infoFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class informacionCFDiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoResult;
        
        public informacionCFDiResponse() {
        }
        
        public informacionCFDiResponse(string infoResult) {
            this.infoResult = infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class cancelarCFDiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarFolio;
        
        public cancelarCFDiRequest() {
        }
        
        public cancelarCFDiRequest(string cancelarFolio) {
            this.cancelarFolio = cancelarFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class cancelarCFDiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarResult;
        
        public cancelarCFDiResponse() {
        }
        
        public cancelarCFDiResponse(string cancelarResult) {
            this.cancelarResult = cancelarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class obtenerSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saldoInput;
        
        public obtenerSaldoRequest() {
        }
        
        public obtenerSaldoRequest(string saldoInput) {
            this.saldoInput = saldoInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class obtenerSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saldoResult;
        
        public obtenerSaldoResponse() {
        }
        
        public obtenerSaldoResponse(string saldoResult) {
            this.saldoResult = saldoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class solicitarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudFolio;
        
        public solicitarXMLRequest() {
        }
        
        public solicitarXMLRequest(string solicitudFolio) {
            this.solicitudFolio = solicitudFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class solicitarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudResult;
        
        public solicitarXMLResponse() {
        }
        
        public solicitarXMLResponse(string solicitudResult) {
            this.solicitudResult = solicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class probarConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexion;
        
        public probarConexionRequest() {
        }
        
        public probarConexionRequest(string probarConexion) {
            this.probarConexion = probarConexion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class probarConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionResult;
        
        public probarConexionResponse() {
        }
        
        public probarConexionResponse(string probarConexionResult) {
            this.probarConexionResult = probarConexionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class solicitarQRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitud;
        
        public solicitarQRRequest() {
        }
        
        public solicitarQRRequest(string QRsolicitud) {
            this.QRsolicitud = QRsolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class solicitarQRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitudResult;
        
        public solicitarQRResponse() {
        }
        
        public solicitarQRResponse(string QRsolicitudResult) {
            this.QRsolicitudResult = QRsolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class enviarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreosolicitud;
        
        public enviarCorreoRequest() {
        }
        
        public enviarCorreoRequest(string enviarCorreosolicitud) {
            this.enviarCorreosolicitud = enviarCorreosolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class enviarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreosolicitudResult;
        
        public enviarCorreoResponse() {
        }
        
        public enviarCorreoResponse(string enviarCorreosolicitudResult) {
            this.enviarCorreosolicitudResult = enviarCorreosolicitudResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAPIxmlSOAPChannel : EnlaceFiscal.EFService.wsAPIxmlSOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class generarCFDiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public generarCFDiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class informacionCFDiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public informacionCFDiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cancelarCFDiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public cancelarCFDiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class obtenerSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public obtenerSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class solicitarXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public solicitarXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class probarConexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public probarConexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class solicitarQRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public solicitarQRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class enviarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public enviarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAPIxmlSOAPClient : System.ServiceModel.ClientBase<EnlaceFiscal.EFService.wsAPIxmlSOAP>, EnlaceFiscal.EFService.wsAPIxmlSOAP {
        
        private BeginOperationDelegate onBegingenerarCFDiDelegate;
        
        private EndOperationDelegate onEndgenerarCFDiDelegate;
        
        private System.Threading.SendOrPostCallback ongenerarCFDiCompletedDelegate;
        
        private BeginOperationDelegate onBegininformacionCFDiDelegate;
        
        private EndOperationDelegate onEndinformacionCFDiDelegate;
        
        private System.Threading.SendOrPostCallback oninformacionCFDiCompletedDelegate;
        
        private BeginOperationDelegate onBegincancelarCFDiDelegate;
        
        private EndOperationDelegate onEndcancelarCFDiDelegate;
        
        private System.Threading.SendOrPostCallback oncancelarCFDiCompletedDelegate;
        
        private BeginOperationDelegate onBeginobtenerSaldoDelegate;
        
        private EndOperationDelegate onEndobtenerSaldoDelegate;
        
        private System.Threading.SendOrPostCallback onobtenerSaldoCompletedDelegate;
        
        private BeginOperationDelegate onBeginsolicitarXMLDelegate;
        
        private EndOperationDelegate onEndsolicitarXMLDelegate;
        
        private System.Threading.SendOrPostCallback onsolicitarXMLCompletedDelegate;
        
        private BeginOperationDelegate onBeginprobarConexionDelegate;
        
        private EndOperationDelegate onEndprobarConexionDelegate;
        
        private System.Threading.SendOrPostCallback onprobarConexionCompletedDelegate;
        
        private BeginOperationDelegate onBeginsolicitarQRDelegate;
        
        private EndOperationDelegate onEndsolicitarQRDelegate;
        
        private System.Threading.SendOrPostCallback onsolicitarQRCompletedDelegate;
        
        private BeginOperationDelegate onBeginenviarCorreoDelegate;
        
        private EndOperationDelegate onEndenviarCorreoDelegate;
        
        private System.Threading.SendOrPostCallback onenviarCorreoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public wsAPIxmlSOAPClient() : 
                base(wsAPIxmlSOAPClient.GetDefaultBinding(), wsAPIxmlSOAPClient.GetDefaultEndpointAddress()) {
        }
        
        public wsAPIxmlSOAPClient(EndpointConfiguration endpointConfiguration) : 
                base(wsAPIxmlSOAPClient.GetBindingForEndpoint(endpointConfiguration), wsAPIxmlSOAPClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public wsAPIxmlSOAPClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsAPIxmlSOAPClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public wsAPIxmlSOAPClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsAPIxmlSOAPClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public wsAPIxmlSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<generarCFDiCompletedEventArgs> generarCFDiCompleted;
        
        public event System.EventHandler<informacionCFDiCompletedEventArgs> informacionCFDiCompleted;
        
        public event System.EventHandler<cancelarCFDiCompletedEventArgs> cancelarCFDiCompleted;
        
        public event System.EventHandler<obtenerSaldoCompletedEventArgs> obtenerSaldoCompleted;
        
        public event System.EventHandler<solicitarXMLCompletedEventArgs> solicitarXMLCompleted;
        
        public event System.EventHandler<probarConexionCompletedEventArgs> probarConexionCompleted;
        
        public event System.EventHandler<solicitarQRCompletedEventArgs> solicitarQRCompleted;
        
        public event System.EventHandler<enviarCorreoCompletedEventArgs> enviarCorreoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BegingenerarCFDi(EnlaceFiscal.EFService.generarCFDiRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingenerarCFDi(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingenerarCFDi(string generarFolio, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.generarCFDiRequest inValue = new EnlaceFiscal.EFService.generarCFDiRequest();
            inValue.generarFolio = generarFolio;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BegingenerarCFDi(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.generarCFDiResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndgenerarCFDi(System.IAsyncResult result) {
            return base.Channel.EndgenerarCFDi(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndgenerarCFDi(System.IAsyncResult result) {
            EnlaceFiscal.EFService.generarCFDiResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndgenerarCFDi(result);
            return retVal.generarResult;
        }
        
        private System.IAsyncResult OnBegingenerarCFDi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string generarFolio = ((string)(inValues[0]));
            return this.BegingenerarCFDi(generarFolio, callback, asyncState);
        }
        
        private object[] OnEndgenerarCFDi(System.IAsyncResult result) {
            string retVal = this.EndgenerarCFDi(result);
            return new object[] {
                    retVal};
        }
        
        private void OngenerarCFDiCompleted(object state) {
            if ((this.generarCFDiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.generarCFDiCompleted(this, new generarCFDiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void generarCFDiAsync(string generarFolio) {
            this.generarCFDiAsync(generarFolio, null);
        }
        
        public void generarCFDiAsync(string generarFolio, object userState) {
            if ((this.onBegingenerarCFDiDelegate == null)) {
                this.onBegingenerarCFDiDelegate = new BeginOperationDelegate(this.OnBegingenerarCFDi);
            }
            if ((this.onEndgenerarCFDiDelegate == null)) {
                this.onEndgenerarCFDiDelegate = new EndOperationDelegate(this.OnEndgenerarCFDi);
            }
            if ((this.ongenerarCFDiCompletedDelegate == null)) {
                this.ongenerarCFDiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngenerarCFDiCompleted);
            }
            base.InvokeAsync(this.onBegingenerarCFDiDelegate, new object[] {
                        generarFolio}, this.onEndgenerarCFDiDelegate, this.ongenerarCFDiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BegininformacionCFDi(EnlaceFiscal.EFService.informacionCFDiRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegininformacionCFDi(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegininformacionCFDi(string infoFolio, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.informacionCFDiRequest inValue = new EnlaceFiscal.EFService.informacionCFDiRequest();
            inValue.infoFolio = infoFolio;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BegininformacionCFDi(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.informacionCFDiResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndinformacionCFDi(System.IAsyncResult result) {
            return base.Channel.EndinformacionCFDi(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndinformacionCFDi(System.IAsyncResult result) {
            EnlaceFiscal.EFService.informacionCFDiResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndinformacionCFDi(result);
            return retVal.infoResult;
        }
        
        private System.IAsyncResult OnBegininformacionCFDi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string infoFolio = ((string)(inValues[0]));
            return this.BegininformacionCFDi(infoFolio, callback, asyncState);
        }
        
        private object[] OnEndinformacionCFDi(System.IAsyncResult result) {
            string retVal = this.EndinformacionCFDi(result);
            return new object[] {
                    retVal};
        }
        
        private void OninformacionCFDiCompleted(object state) {
            if ((this.informacionCFDiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.informacionCFDiCompleted(this, new informacionCFDiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void informacionCFDiAsync(string infoFolio) {
            this.informacionCFDiAsync(infoFolio, null);
        }
        
        public void informacionCFDiAsync(string infoFolio, object userState) {
            if ((this.onBegininformacionCFDiDelegate == null)) {
                this.onBegininformacionCFDiDelegate = new BeginOperationDelegate(this.OnBegininformacionCFDi);
            }
            if ((this.onEndinformacionCFDiDelegate == null)) {
                this.onEndinformacionCFDiDelegate = new EndOperationDelegate(this.OnEndinformacionCFDi);
            }
            if ((this.oninformacionCFDiCompletedDelegate == null)) {
                this.oninformacionCFDiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OninformacionCFDiCompleted);
            }
            base.InvokeAsync(this.onBegininformacionCFDiDelegate, new object[] {
                        infoFolio}, this.onEndinformacionCFDiDelegate, this.oninformacionCFDiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BegincancelarCFDi(EnlaceFiscal.EFService.cancelarCFDiRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincancelarCFDi(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegincancelarCFDi(string cancelarFolio, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.cancelarCFDiRequest inValue = new EnlaceFiscal.EFService.cancelarCFDiRequest();
            inValue.cancelarFolio = cancelarFolio;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BegincancelarCFDi(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.cancelarCFDiResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndcancelarCFDi(System.IAsyncResult result) {
            return base.Channel.EndcancelarCFDi(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndcancelarCFDi(System.IAsyncResult result) {
            EnlaceFiscal.EFService.cancelarCFDiResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndcancelarCFDi(result);
            return retVal.cancelarResult;
        }
        
        private System.IAsyncResult OnBegincancelarCFDi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cancelarFolio = ((string)(inValues[0]));
            return this.BegincancelarCFDi(cancelarFolio, callback, asyncState);
        }
        
        private object[] OnEndcancelarCFDi(System.IAsyncResult result) {
            string retVal = this.EndcancelarCFDi(result);
            return new object[] {
                    retVal};
        }
        
        private void OncancelarCFDiCompleted(object state) {
            if ((this.cancelarCFDiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.cancelarCFDiCompleted(this, new cancelarCFDiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void cancelarCFDiAsync(string cancelarFolio) {
            this.cancelarCFDiAsync(cancelarFolio, null);
        }
        
        public void cancelarCFDiAsync(string cancelarFolio, object userState) {
            if ((this.onBegincancelarCFDiDelegate == null)) {
                this.onBegincancelarCFDiDelegate = new BeginOperationDelegate(this.OnBegincancelarCFDi);
            }
            if ((this.onEndcancelarCFDiDelegate == null)) {
                this.onEndcancelarCFDiDelegate = new EndOperationDelegate(this.OnEndcancelarCFDi);
            }
            if ((this.oncancelarCFDiCompletedDelegate == null)) {
                this.oncancelarCFDiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncancelarCFDiCompleted);
            }
            base.InvokeAsync(this.onBegincancelarCFDiDelegate, new object[] {
                        cancelarFolio}, this.onEndcancelarCFDiDelegate, this.oncancelarCFDiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BeginobtenerSaldo(EnlaceFiscal.EFService.obtenerSaldoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginobtenerSaldo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginobtenerSaldo(string saldoInput, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.obtenerSaldoRequest inValue = new EnlaceFiscal.EFService.obtenerSaldoRequest();
            inValue.saldoInput = saldoInput;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BeginobtenerSaldo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.obtenerSaldoResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndobtenerSaldo(System.IAsyncResult result) {
            return base.Channel.EndobtenerSaldo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndobtenerSaldo(System.IAsyncResult result) {
            EnlaceFiscal.EFService.obtenerSaldoResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndobtenerSaldo(result);
            return retVal.saldoResult;
        }
        
        private System.IAsyncResult OnBeginobtenerSaldo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string saldoInput = ((string)(inValues[0]));
            return this.BeginobtenerSaldo(saldoInput, callback, asyncState);
        }
        
        private object[] OnEndobtenerSaldo(System.IAsyncResult result) {
            string retVal = this.EndobtenerSaldo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnobtenerSaldoCompleted(object state) {
            if ((this.obtenerSaldoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.obtenerSaldoCompleted(this, new obtenerSaldoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void obtenerSaldoAsync(string saldoInput) {
            this.obtenerSaldoAsync(saldoInput, null);
        }
        
        public void obtenerSaldoAsync(string saldoInput, object userState) {
            if ((this.onBeginobtenerSaldoDelegate == null)) {
                this.onBeginobtenerSaldoDelegate = new BeginOperationDelegate(this.OnBeginobtenerSaldo);
            }
            if ((this.onEndobtenerSaldoDelegate == null)) {
                this.onEndobtenerSaldoDelegate = new EndOperationDelegate(this.OnEndobtenerSaldo);
            }
            if ((this.onobtenerSaldoCompletedDelegate == null)) {
                this.onobtenerSaldoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnobtenerSaldoCompleted);
            }
            base.InvokeAsync(this.onBeginobtenerSaldoDelegate, new object[] {
                        saldoInput}, this.onEndobtenerSaldoDelegate, this.onobtenerSaldoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BeginsolicitarXML(EnlaceFiscal.EFService.solicitarXMLRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsolicitarXML(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsolicitarXML(string solicitudFolio, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.solicitarXMLRequest inValue = new EnlaceFiscal.EFService.solicitarXMLRequest();
            inValue.solicitudFolio = solicitudFolio;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BeginsolicitarXML(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.solicitarXMLResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndsolicitarXML(System.IAsyncResult result) {
            return base.Channel.EndsolicitarXML(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndsolicitarXML(System.IAsyncResult result) {
            EnlaceFiscal.EFService.solicitarXMLResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndsolicitarXML(result);
            return retVal.solicitudResult;
        }
        
        private System.IAsyncResult OnBeginsolicitarXML(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string solicitudFolio = ((string)(inValues[0]));
            return this.BeginsolicitarXML(solicitudFolio, callback, asyncState);
        }
        
        private object[] OnEndsolicitarXML(System.IAsyncResult result) {
            string retVal = this.EndsolicitarXML(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsolicitarXMLCompleted(object state) {
            if ((this.solicitarXMLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.solicitarXMLCompleted(this, new solicitarXMLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void solicitarXMLAsync(string solicitudFolio) {
            this.solicitarXMLAsync(solicitudFolio, null);
        }
        
        public void solicitarXMLAsync(string solicitudFolio, object userState) {
            if ((this.onBeginsolicitarXMLDelegate == null)) {
                this.onBeginsolicitarXMLDelegate = new BeginOperationDelegate(this.OnBeginsolicitarXML);
            }
            if ((this.onEndsolicitarXMLDelegate == null)) {
                this.onEndsolicitarXMLDelegate = new EndOperationDelegate(this.OnEndsolicitarXML);
            }
            if ((this.onsolicitarXMLCompletedDelegate == null)) {
                this.onsolicitarXMLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsolicitarXMLCompleted);
            }
            base.InvokeAsync(this.onBeginsolicitarXMLDelegate, new object[] {
                        solicitudFolio}, this.onEndsolicitarXMLDelegate, this.onsolicitarXMLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BeginprobarConexion(EnlaceFiscal.EFService.probarConexionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginprobarConexion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginprobarConexion(string probarConexion, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.probarConexionRequest inValue = new EnlaceFiscal.EFService.probarConexionRequest();
            inValue.probarConexion = probarConexion;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BeginprobarConexion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.probarConexionResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndprobarConexion(System.IAsyncResult result) {
            return base.Channel.EndprobarConexion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndprobarConexion(System.IAsyncResult result) {
            EnlaceFiscal.EFService.probarConexionResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndprobarConexion(result);
            return retVal.probarConexionResult;
        }
        
        private System.IAsyncResult OnBeginprobarConexion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string probarConexion = ((string)(inValues[0]));
            return this.BeginprobarConexion(probarConexion, callback, asyncState);
        }
        
        private object[] OnEndprobarConexion(System.IAsyncResult result) {
            string retVal = this.EndprobarConexion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnprobarConexionCompleted(object state) {
            if ((this.probarConexionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.probarConexionCompleted(this, new probarConexionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void probarConexionAsync(string probarConexion) {
            this.probarConexionAsync(probarConexion, null);
        }
        
        public void probarConexionAsync(string probarConexion, object userState) {
            if ((this.onBeginprobarConexionDelegate == null)) {
                this.onBeginprobarConexionDelegate = new BeginOperationDelegate(this.OnBeginprobarConexion);
            }
            if ((this.onEndprobarConexionDelegate == null)) {
                this.onEndprobarConexionDelegate = new EndOperationDelegate(this.OnEndprobarConexion);
            }
            if ((this.onprobarConexionCompletedDelegate == null)) {
                this.onprobarConexionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnprobarConexionCompleted);
            }
            base.InvokeAsync(this.onBeginprobarConexionDelegate, new object[] {
                        probarConexion}, this.onEndprobarConexionDelegate, this.onprobarConexionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BeginsolicitarQR(EnlaceFiscal.EFService.solicitarQRRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsolicitarQR(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsolicitarQR(string QRsolicitud, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.solicitarQRRequest inValue = new EnlaceFiscal.EFService.solicitarQRRequest();
            inValue.QRsolicitud = QRsolicitud;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BeginsolicitarQR(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.solicitarQRResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndsolicitarQR(System.IAsyncResult result) {
            return base.Channel.EndsolicitarQR(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndsolicitarQR(System.IAsyncResult result) {
            EnlaceFiscal.EFService.solicitarQRResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndsolicitarQR(result);
            return retVal.QRsolicitudResult;
        }
        
        private System.IAsyncResult OnBeginsolicitarQR(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string QRsolicitud = ((string)(inValues[0]));
            return this.BeginsolicitarQR(QRsolicitud, callback, asyncState);
        }
        
        private object[] OnEndsolicitarQR(System.IAsyncResult result) {
            string retVal = this.EndsolicitarQR(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsolicitarQRCompleted(object state) {
            if ((this.solicitarQRCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.solicitarQRCompleted(this, new solicitarQRCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void solicitarQRAsync(string QRsolicitud) {
            this.solicitarQRAsync(QRsolicitud, null);
        }
        
        public void solicitarQRAsync(string QRsolicitud, object userState) {
            if ((this.onBeginsolicitarQRDelegate == null)) {
                this.onBeginsolicitarQRDelegate = new BeginOperationDelegate(this.OnBeginsolicitarQR);
            }
            if ((this.onEndsolicitarQRDelegate == null)) {
                this.onEndsolicitarQRDelegate = new EndOperationDelegate(this.OnEndsolicitarQR);
            }
            if ((this.onsolicitarQRCompletedDelegate == null)) {
                this.onsolicitarQRCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsolicitarQRCompleted);
            }
            base.InvokeAsync(this.onBeginsolicitarQRDelegate, new object[] {
                        QRsolicitud}, this.onEndsolicitarQRDelegate, this.onsolicitarQRCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult EnlaceFiscal.EFService.wsAPIxmlSOAP.BeginenviarCorreo(EnlaceFiscal.EFService.enviarCorreoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginenviarCorreo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginenviarCorreo(string enviarCorreosolicitud, System.AsyncCallback callback, object asyncState) {
            EnlaceFiscal.EFService.enviarCorreoRequest inValue = new EnlaceFiscal.EFService.enviarCorreoRequest();
            inValue.enviarCorreosolicitud = enviarCorreosolicitud;
            return ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).BeginenviarCorreo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnlaceFiscal.EFService.enviarCorreoResponse EnlaceFiscal.EFService.wsAPIxmlSOAP.EndenviarCorreo(System.IAsyncResult result) {
            return base.Channel.EndenviarCorreo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndenviarCorreo(System.IAsyncResult result) {
            EnlaceFiscal.EFService.enviarCorreoResponse retVal = ((EnlaceFiscal.EFService.wsAPIxmlSOAP)(this)).EndenviarCorreo(result);
            return retVal.enviarCorreosolicitudResult;
        }
        
        private System.IAsyncResult OnBeginenviarCorreo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string enviarCorreosolicitud = ((string)(inValues[0]));
            return this.BeginenviarCorreo(enviarCorreosolicitud, callback, asyncState);
        }
        
        private object[] OnEndenviarCorreo(System.IAsyncResult result) {
            string retVal = this.EndenviarCorreo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnenviarCorreoCompleted(object state) {
            if ((this.enviarCorreoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.enviarCorreoCompleted(this, new enviarCorreoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void enviarCorreoAsync(string enviarCorreosolicitud) {
            this.enviarCorreoAsync(enviarCorreosolicitud, null);
        }
        
        public void enviarCorreoAsync(string enviarCorreosolicitud, object userState) {
            if ((this.onBeginenviarCorreoDelegate == null)) {
                this.onBeginenviarCorreoDelegate = new BeginOperationDelegate(this.OnBeginenviarCorreo);
            }
            if ((this.onEndenviarCorreoDelegate == null)) {
                this.onEndenviarCorreoDelegate = new EndOperationDelegate(this.OnEndenviarCorreo);
            }
            if ((this.onenviarCorreoCompletedDelegate == null)) {
                this.onenviarCorreoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnenviarCorreoCompleted);
            }
            base.InvokeAsync(this.onBeginenviarCorreoDelegate, new object[] {
                        enviarCorreosolicitud}, this.onEndenviarCorreoDelegate, this.onenviarCorreoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override EnlaceFiscal.EFService.wsAPIxmlSOAP CreateChannel() {
            return new wsAPIxmlSOAPClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EFPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EFPort)) {
                return new System.ServiceModel.EndpointAddress("https://api.enlacefiscal.com/soap/serviceCFDi.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return wsAPIxmlSOAPClient.GetBindingForEndpoint(EndpointConfiguration.EFPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return wsAPIxmlSOAPClient.GetEndpointAddress(EndpointConfiguration.EFPort);
        }
        
        private class wsAPIxmlSOAPClientChannel : ChannelBase<EnlaceFiscal.EFService.wsAPIxmlSOAP>, EnlaceFiscal.EFService.wsAPIxmlSOAP {
            
            public wsAPIxmlSOAPClientChannel(System.ServiceModel.ClientBase<EnlaceFiscal.EFService.wsAPIxmlSOAP> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingenerarCFDi(EnlaceFiscal.EFService.generarCFDiRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("generarCFDi", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.generarCFDiResponse EndgenerarCFDi(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.generarCFDiResponse _result = ((EnlaceFiscal.EFService.generarCFDiResponse)(base.EndInvoke("generarCFDi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegininformacionCFDi(EnlaceFiscal.EFService.informacionCFDiRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("informacionCFDi", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.informacionCFDiResponse EndinformacionCFDi(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.informacionCFDiResponse _result = ((EnlaceFiscal.EFService.informacionCFDiResponse)(base.EndInvoke("informacionCFDi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegincancelarCFDi(EnlaceFiscal.EFService.cancelarCFDiRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("cancelarCFDi", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.cancelarCFDiResponse EndcancelarCFDi(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.cancelarCFDiResponse _result = ((EnlaceFiscal.EFService.cancelarCFDiResponse)(base.EndInvoke("cancelarCFDi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginobtenerSaldo(EnlaceFiscal.EFService.obtenerSaldoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("obtenerSaldo", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.obtenerSaldoResponse EndobtenerSaldo(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.obtenerSaldoResponse _result = ((EnlaceFiscal.EFService.obtenerSaldoResponse)(base.EndInvoke("obtenerSaldo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsolicitarXML(EnlaceFiscal.EFService.solicitarXMLRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("solicitarXML", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.solicitarXMLResponse EndsolicitarXML(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.solicitarXMLResponse _result = ((EnlaceFiscal.EFService.solicitarXMLResponse)(base.EndInvoke("solicitarXML", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginprobarConexion(EnlaceFiscal.EFService.probarConexionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("probarConexion", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.probarConexionResponse EndprobarConexion(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.probarConexionResponse _result = ((EnlaceFiscal.EFService.probarConexionResponse)(base.EndInvoke("probarConexion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsolicitarQR(EnlaceFiscal.EFService.solicitarQRRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("solicitarQR", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.solicitarQRResponse EndsolicitarQR(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.solicitarQRResponse _result = ((EnlaceFiscal.EFService.solicitarQRResponse)(base.EndInvoke("solicitarQR", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginenviarCorreo(EnlaceFiscal.EFService.enviarCorreoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("enviarCorreo", _args, callback, asyncState);
                return _result;
            }
            
            public EnlaceFiscal.EFService.enviarCorreoResponse EndenviarCorreo(System.IAsyncResult result) {
                object[] _args = new object[0];
                EnlaceFiscal.EFService.enviarCorreoResponse _result = ((EnlaceFiscal.EFService.enviarCorreoResponse)(base.EndInvoke("enviarCorreo", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            EFPort,
        }
    }
}
